# shellcheck shell=bash
# =============================================================================
# lib/mdns.sh — Avahi/mDNS publishing of the appliance hostnames so LAN clients
# resolve them without any DNS configuration.
#
# Used with HOST_MODE=mdns, and with HOST_MODE=proxy whenever LOCAL_DOMAIN is
# kept (the default) — a published box still answers on the LAN under its own
# `.local` names, which is the whole point: nothing on the customer side has to
# change, and the box keeps working with the WAN down.
#
# What is published is always the `.local` set and never the public one:
# nss-mdns routes only `.local` to mDNS, so advertising a routable name here
# would announce something no client ever asks us about.
#
# Design: a single self-contained WATCHER service. It polls the current LAN IP
# every 5s and, only when it actually changes, (re)publishes the mDNS names and
# rollout-restarts livekit (whose initContainer re-detects the LAN IP for
# WebRTC media). No NetworkManager/networkd dispatcher hooks: at boot NM fires
# dozens of events (including for every veth/cni iface), and a hook doing
# `systemctl restart` per event trips systemd's start rate-limit and leaves the
# unit permanently dead in `start-limit-hit` (observed on the 2026-07-02 spark
# reboot). Polling is storm-proof, works with any network manager, and offline
# is just "no IP yet — keep waiting".
# =============================================================================

# --- 5. mDNS (Avahi) ---------------------------------------------------------
setup_mdns() {
  # Which names, if any, this box publishes over multicast:
  #   mdns  : the four hostnames, which gather_hosts() has forced into `.local`.
  #   proxy : the LAN set kept beside the public names (empty if LOCAL_DOMAIN="").
  #   dns   : none — the customer's DNS is authoritative for these names, and a
  #           second answer over multicast is a liability, not a fallback.
  # `[[ test ]] && assignment` would be the obvious way to write the proxy arm
  # and would kill the installer: the AND-list returns the failed test's status
  # and `set -e` takes it. if/fi throughout.
  local names="" shown=""
  if [[ "$HOST_MODE" == "mdns" ]]; then
    names="$DOMAIN $APP_HOST $OFFICE_HOST $LIVEKIT_HOST $TURN_HOST"
    shown="$APP_HOST"
  elif [[ "$HOST_MODE" == "proxy" && -n "${LOCAL_APP_HOST:-}" ]]; then
    names="$LOCAL_DOMAIN $LOCAL_APP_HOST $LOCAL_OFFICE_HOST $LOCAL_LIVEKIT_HOST $LOCAL_TURN_HOST"
    shown="$LOCAL_APP_HOST"
  fi
  if [[ -z "$names" ]]; then
    disable_mdns
    return 0
  fi
  log "mDNS (Avahi) — $shown + 3 more"
  if ! have avahi-daemon; then
    apt-get update -y || warn "apt-get update failed (stale cache?) — install may fail."
    apt-get install -y avahi-daemon avahi-utils \
      || die "avahi install failed (network/apt?)."
  fi
  systemctl enable --now avahi-daemon

  cat > /usr/local/bin/suite366-avahi-aliases.sh <<EOF
#!/usr/bin/env bash
# Generated by install.sh — mDNS watcher: publishes Suite 366 names on the
# CURRENT LAN IP and refreshes them (plus livekit's advertised media IP)
# whenever the IP changes. See lib/mdns.sh for the design rationale.
set -u
NAMES="$names"
STATE=/run/suite366-mdns.ip   # survives service restarts, wiped at boot

current_ip() { ip route get 1.1.1.1 2>/dev/null | awk '{print \$7; exit}'; }
unpublish()  { pkill -P \$\$ -x avahi-publish 2>/dev/null; }
publish()    { local f; for f in \$NAMES; do avahi-publish -a -R "\$f" "\$1" & done; }

trap 'unpublish; exit 0' TERM INT

PUBLISHED=""   # IP the running avahi-publish processes advertise ("" = none)
while :; do
  IP="\$(current_ip)"
  if [ "\${IP:-}" != "\$PUBLISHED" ]; then
    unpublish
    if [ -n "\${IP:-}" ]; then
      echo "suite366-mdns: publishing \$NAMES -> \$IP"
      publish "\$IP"
      # livekit advertises the LAN IP for WebRTC media (rtc.node_ip, rendered
      # by its initContainer): recreate its pod when the LAN IP truly changed
      # so the initContainer re-detects it. Delete the POD by its selector
      # label (app=<name>-livekit) — the label lives on pods, NOT on the
      # Deployment, so a \`rollout restart deploy -l ...\` would silently match
      # nothing. This also self-heals the boot race where the initContainer
      # grabs a transient IP (e.g. WiFi) before the default route settles.
      # \$STATE persists across service restarts so an install.sh re-run does
      # not bounce livekit; at boot the file is absent and the deletion is a
      # harmless no-op if k3s isn't up yet (|| true).
      if [ "\$(cat "\$STATE" 2>/dev/null)" != "\$IP" ]; then
        KUBECONFIG=$KUBECONFIG_PATH k3s kubectl -n $NAMESPACE delete pod \\
          -l app=$RELEASE-livekit --ignore-not-found >/dev/null 2>&1 || true
        echo "\$IP" > "\$STATE"
      fi
    else
      echo "suite366-mdns: no LAN IP (offline?) — waiting"
    fi
    PUBLISHED="\${IP:-}"
  fi
  sleep 5
done
EOF
  chmod +x /usr/local/bin/suite366-avahi-aliases.sh
  fetch "dns/avahi-aliases.service" > /etc/systemd/system/suite366-avahi-aliases.service

  # Drop the dispatcher hooks from previous versions (restart storms at boot —
  # see header). The watcher replaces them.
  rm -f /etc/NetworkManager/dispatcher.d/90-suite366-mdns \
        /etc/networkd-dispatcher/routable.d/90-suite366-mdns

  systemctl daemon-reload
  systemctl reset-failed suite366-avahi-aliases.service 2>/dev/null || true
  systemctl enable suite366-avahi-aliases.service
  systemctl restart suite366-avahi-aliases.service
}


# Remove a publisher installed by an earlier run. This is not defensive noise:
# re-running install.sh to MOVE a box from `.local` to the customer's domain
# would otherwise leave the old watcher alive, still answering on the LAN for
# names the appliance no longer serves.
disable_mdns() {
  if [[ "$HOST_MODE" == "proxy" ]]; then
    info "mDNS not used (HOST_MODE=proxy, LOCAL_DOMAIN empty) — only the public names are served."
  else
    info "mDNS not used (HOST_MODE=$HOST_MODE) — the names are resolved by your DNS."
  fi
  if [[ -e /etc/systemd/system/suite366-avahi-aliases.service ]]; then
    log "Removing the mDNS publisher installed by a previous run"
    systemctl disable --now suite366-avahi-aliases.service >/dev/null 2>&1 || true
    rm -f /etc/systemd/system/suite366-avahi-aliases.service \
          /usr/local/bin/suite366-avahi-aliases.sh \
          /run/suite366-mdns.ip
    systemctl daemon-reload
    info "suite366-avahi-aliases removed (the avahi-daemon package is left alone)."
  fi
}
