# shellcheck shell=bash
# =============================================================================
# lib/mdns.sh — Avahi/mDNS publishing of *.$DOMAIN so LAN clients resolve the
# appliance without DNS config.
# =============================================================================

# --- 5. mDNS (Avahi) ---------------------------------------------------------
setup_mdns() {
  log "mDNS (Avahi) — *.$DOMAIN"
  if ! have avahi-daemon; then
    apt-get update -y || warn "apt-get update failed (stale cache?) — install may fail."
    apt-get install -y avahi-daemon avahi-utils \
      || die "avahi install failed (network/apt?)."
  fi
  systemctl enable --now avahi-daemon

  # The IP is resolved at RUNTIME (not baked at install) so the *.local names
  # follow the current LAN — a DHCP change or a WiFi<->Ethernet switch just
  # needs the service restarted (done by the dispatcher hook below). Offline
  # (no default route) is handled gracefully: nothing is published, no crash.
  cat > /usr/local/bin/suite366-avahi-aliases.sh <<EOF
#!/usr/bin/env bash
# Generated by install.sh — publishes Suite 366 mDNS names on the CURRENT LAN IP.
set -eu
IP="\$(ip route get 1.1.1.1 2>/dev/null | awk '{print \$7; exit}')"
if [ -z "\${IP:-}" ]; then
  echo "suite366-mdns: no LAN IP (offline?) — not publishing *.local names"
  # Stay alive so systemd keeps the unit active; the dispatcher restarts us
  # when connectivity returns.
  exec sleep infinity
fi
echo "suite366-mdns: publishing *.$DOMAIN -> \$IP"
for fqdn in $DOMAIN drive.$DOMAIN office.$DOMAIN livekit.$DOMAIN turn.$DOMAIN; do
  avahi-publish -a -R "\$fqdn" "\$IP" &
done
wait
EOF
  chmod +x /usr/local/bin/suite366-avahi-aliases.sh
  fetch "dns/avahi-aliases.service" > /etc/systemd/system/suite366-avahi-aliases.service

  # Re-publish on network change. NetworkManager (DGX OS default) and
  # networkd-dispatcher are both supported — install into whichever exists.
  local hook='#!/usr/bin/env bash
# Generated by install.sh — restart mDNS aliases when the network changes so
# *.local tracks the current LAN IP.
systemctl restart suite366-avahi-aliases.service 2>/dev/null || true
'
  if [[ -d /etc/NetworkManager/dispatcher.d ]]; then
    printf '%s' "$hook" > /etc/NetworkManager/dispatcher.d/90-suite366-mdns
    chmod +x /etc/NetworkManager/dispatcher.d/90-suite366-mdns
  fi
  if [[ -d /etc/networkd-dispatcher/routable.d ]]; then
    printf '%s' "$hook" > /etc/networkd-dispatcher/routable.d/90-suite366-mdns
    chmod +x /etc/networkd-dispatcher/routable.d/90-suite366-mdns
  fi

  systemctl daemon-reload
  systemctl enable --now suite366-avahi-aliases.service
}
