# shellcheck shell=bash
# =============================================================================
# lib/network.sh — stable internal IP on an always-up `dummy` interface.
#
# This is what makes the appliance survive a network change or going offline:
# k3s (node-ip/flannel), vLLM (port bind) and the app (VLLM_BASE_URL) are all
# wired to SUITE_IP on SUITE_IFACE instead of the LAN IP. A dummy interface is
# always UP, exists with zero physical connectivity, and never changes — so the
# cluster's internal identity is constant no matter what the LAN does.
# =============================================================================

# --- 1. Stable internal IP ---------------------------------------------------
setup_stable_ip() {
  log "Stable internal IP ($SUITE_IP on $SUITE_IFACE)"

  # Boot-time bring-up script (values baked in, like the mDNS one). Idempotent:
  # safe to re-run, and re-creates the interface after a reboot.
  cat > /usr/local/bin/suite366-net-up.sh <<EOF
#!/usr/bin/env bash
# Generated by install.sh — brings up the stable internal interface.
set -eu
IFACE="$SUITE_IFACE"
CIDR="$SUITE_IP/32"
ip link show "\$IFACE" >/dev/null 2>&1 || ip link add "\$IFACE" type dummy
ip -4 addr show dev "\$IFACE" | grep -qw "${SUITE_IP}" || ip addr add "\$CIDR" dev "\$IFACE"
ip link set "\$IFACE" up
EOF
  chmod +x /usr/local/bin/suite366-net-up.sh

  # Ordered BEFORE k3s and docker so node-ip/flannel and the vLLM port bind
  # always find the interface present. DefaultDependencies=no keeps it in the
  # early-boot transaction; it does not need the network to be online.
  cat > /etc/systemd/system/suite366-net.service <<'EOF'
[Unit]
Description=Suite 366 — stable internal IP (dummy interface)
DefaultDependencies=no
After=systemd-sysctl.service
Before=network-pre.target k3s.service docker.service
Wants=network-pre.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/local/bin/suite366-net-up.sh

[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload
  systemctl enable --now suite366-net.service \
    || die "Failed to bring up $SUITE_IFACE ($SUITE_IP)."
  # Verify — everything downstream depends on this IP being reachable locally.
  ip -4 addr show dev "$SUITE_IFACE" | grep -qw "$SUITE_IP" \
    || die "$SUITE_IP not present on $SUITE_IFACE after start."
  info "Stable IP ready: $SUITE_IP on $SUITE_IFACE."
}
