# shellcheck shell=bash
# =============================================================================
# lib/vllm.sh — vLLM ×2 (generative + embeddings), ×3 with transcription, +
# nginx unifying proxy on the Docker host, wired to the Blackwell GPU and
# managed by a systemd unit.
# =============================================================================

# --- The host layer: one artefact, laid down whole -----------------------------
# Everything the vLLM stack needs on the host — switch-model.sh, the profile
# table, the compose, the nginx config, the container entrypoint, the Flash-Next
# patch set and the transcription image context — travels as ONE file,
# host-layer.sh (generated by tools/bundle-host-layer.sh, pinned in channel.json
# as host_layer_sha256). update.sh lays the same file down on a running box, so
# a fleet installed at different dates converges on the same host side without
# anyone re-running install.sh. The stamp records which bundle a box carries;
# update.sh compares it with the channel to know when to act.
#
# Laid down whatever the active profile: switching to Flash-Next later must not
# require reaching the deploy repo again, on a box that may have no route to it.
HOST_LAYER_STAMP="$DATA_DIR/llm/.host-layer.sha256"
fetch_host_layer() {
  local tmp; tmp="$(mktemp)"
  fetch "host-layer.sh" > "$tmp"
  bash -n "$tmp" || die "host-layer.sh does not parse — refusing to lay it down."
  bash "$tmp" extract "$DATA_DIR" || die "host-layer.sh could not unpack into $DATA_DIR."
  sha256sum "$tmp" | awk '{print $1}' > "$HOST_LAYER_STAMP"
  chmod 0644 "$HOST_LAYER_STAMP"
  rm -f "$tmp"
  info "host layer laid down (switch-model.sh + llm/, stamp $(cut -c1-12 "$HOST_LAYER_STAMP"))."
}

# --- The engine image: the unified one, pulled or built ---------------------
# Three of the four profiles, the transcription engine and the embed run ONE
# image, llm/unified/Dockerfile: the official vLLM image plus exllamav3 and the
# EXL3 plugin (OrcaSAQ), the audio extras (transcription) and Gemma's chat
# template. CI publishes it (ghcr.io/scriptor-group/suite-366-vllm) and the
# channel names it in vllm_image, so the normal case is a pull. The label the
# Dockerfile sets is how a box tells it from a PLAIN upstream image: handed one
# (an offline package, an older channel, an operator's VLLM_IMAGE), the box
# builds the same Dockerfile over it, once per tag — ~5 min on the Spark's 20
# cores, with the engines down (switch-model.sh build_with_engines_down does
# that on a running box; at install nothing runs yet).
# switch-model.sh carries the same two functions: it has no lib/ to source.
image_is_unified() { # image_is_unified IMAGE -> the image carries the unified label
  [[ -n "$(docker image inspect -f "{{index .Config.Labels \"$LLM_UNIFIED_LABEL\"}}" "$1" 2>/dev/null)" ]]
}
ensure_engine_image() { # -> sets ENGINE_IMAGE; pulls or builds what is missing
  local ctx="$DATA_DIR/llm" tag
  if ! docker image inspect "$VLLM_IMAGE" >/dev/null 2>&1; then
    log "Pulling $VLLM_IMAGE"
    docker pull -q "$VLLM_IMAGE" >/dev/null || die "docker pull $VLLM_IMAGE failed."
  fi
  if image_is_unified "$VLLM_IMAGE"; then
    ENGINE_IMAGE="$VLLM_IMAGE"
    info "engine image: $ENGINE_IMAGE (unified, revision $(docker image inspect -f "{{index .Config.Labels \"$LLM_UNIFIED_LABEL\"}}" "$VLLM_IMAGE"))."
    return 0
  fi
  tag="$(llm_unified_image "$VLLM_IMAGE")"
  ENGINE_IMAGE="$tag"
  if docker image inspect "$tag" >/dev/null 2>&1; then
    info "engine image: $tag (built here over $VLLM_IMAGE)."
    return 0
  fi
  [[ -f "$ctx/unified/Dockerfile" ]] || die "$ctx/unified/Dockerfile missing — the host layer is incomplete."
  log "Building $tag over $VLLM_IMAGE (llm/unified/Dockerfile: exllamav3 compiles in ~3 min on the 20 cores, ~5 min in all)"
  # stdout (the image id) is noise; stderr is where a failing step explains itself.
  docker build -q -f "$ctx/unified/Dockerfile" --build-arg "BASE_IMAGE=$VLLM_IMAGE" \
    --build-arg "UNIFIED_REV=$LLM_UNIFIED_IMAGE_REV" -t "$tag" "$ctx" >/dev/null \
    || die "docker build of $tag failed — see llm/unified/README.md"
}

# --- Flash-Next's own image, built on the box -------------------------------
# The only profile with an image of its own (llm/profiles.sh LLM_P_NEEDS_BUILD):
# it fits on one Spark only with its 47.7 GiB n-gram table served from the NVMe
# by mmap, a vLLM patch set (llm/flash-next/) laid over the v0.29.0 image it was
# written for. No registry holds it: built here, once per tag, and the tag
# names its inputs so a refreshed patch set rebuilds. switch-model.sh
# (ensure_profile_images) does the same on a running box.
build_profile_image() { # build_profile_image TAG BUILD_DIR
  local tag="$1" ctx="$DATA_DIR/llm/$2"
  if docker image inspect "$tag" >/dev/null 2>&1; then
    info "vLLM image $tag already built."
    return 0
  fi
  [[ -f "$ctx/Dockerfile" ]] || die "$ctx/Dockerfile missing — the host layer is incomplete."
  log "Building $tag ($LLM_FLASH_NEXT_BASE_IMAGE + llm/$2/ — its Dockerfile says how long)"
  docker pull -q "$LLM_FLASH_NEXT_BASE_IMAGE" >/dev/null
  # llm/flash-next/Dockerfile pins its own FROM (the vendored recipe, as is);
  # the build argument is passed for a Dockerfile that would take one.
  docker build -q --build-arg "BASE_IMAGE=$LLM_FLASH_NEXT_BASE_IMAGE" -t "$tag" "$ctx" >/dev/null \
    || die "docker build of $tag failed — see llm/$2/README.md"
}

# Only Flash-Next asks for this: with it up the box has no memory headroom
# (117/121 GiB used) and 7-10 GiB of swap in use, and at the default swappiness
# of 60 pages were read back from swap during every generation. The other two
# profiles leave the host default alone — and REMOVE the drop-in, so a box that
# switched away does not keep a tuning meant for a model it no longer runs.
VLLM_SYSCTL_FILE="${VLLM_SYSCTL_FILE:-/etc/sysctl.d/90-suite366-vllm.conf}"
apply_vllm_sysctl() { # apply_vllm_sysctl [SWAPPINESS]  (empty = restore default)
  local want="${1:-}"
  if [[ -z "$want" ]]; then
    [[ -f "$VLLM_SYSCTL_FILE" ]] || return 0
    rm -f "$VLLM_SYSCTL_FILE"
    info "vm.swappiness drop-in removed (this profile does not need it)."
    return 0
  fi
  printf 'vm.swappiness = %s\n' "$want" > "$VLLM_SYSCTL_FILE"
  sysctl -q -w "vm.swappiness=$want" >/dev/null 2>&1 || true
}

# --- 2. vLLM stack (Docker host) --------------------------------------------
deploy_vllm() {
  log "vLLM ×2 + nginx proxy (Docker host, Blackwell GPU)"
  # $CACHE_DIR holds the JIT state the compose mounts into both vLLM containers
  # (torch.compile artifacts, FlashInfer autotune + JIT cubins, Triton
  # kernels). It is what turns a 257 s restart into a 96 s one; safe to wipe.
  mkdir -p "$MODELS_DIR" "$DATA_DIR/llm" "$CACHE_DIR/vllm" "$CACHE_DIR/flashinfer" "$CACHE_DIR/triton"
  # The compose, the nginx config, switch-model.sh (an OPERATOR script, at
  # $DATA_DIR next to update.sh and backup.sh: `sudo /opt/suite366/switch-model.sh`),
  # the profile table, the entrypoint, Gemma's chat template and the two image
  # build contexts — one bundle, the same one update.sh lays down later.
  fetch_host_layer
  # The engine image, now that docker can answer whether VLLM_IMAGE is the
  # unified one; then the profile again, with the real answer. An image the
  # operator named explicitly (VLLM_LLM_IMAGE / VLLM_STT_IMAGE) stays.
  ensure_engine_image
  llm_profile_apply "$LLM_PROFILE" "$ENGINE_IMAGE" "$FLASH_NEXT_IMAGE"
  [[ -n "${VLLM_LLM_IMAGE_SET:-}" ]] || VLLM_LLM_IMAGE="$LLM_P_IMAGE"
  [[ -n "${VLLM_STT_IMAGE_SET:-}" ]] || VLLM_STT_IMAGE="$ENGINE_IMAGE"
  # `if`, not `[[ ]] &&`: as the last command of a function the && form
  # returns 1 when the test is false and `set -e` kills the install.
  if [[ "$LLM_P_NEEDS_BUILD" == "1" ]]; then build_profile_image "$VLLM_LLM_IMAGE" "$LLM_P_BUILD_DIR"; fi
  apply_vllm_sysctl "$LLM_P_SWAPPINESS"
  local env_file="$DATA_DIR/llm/.env" env_old=""
  [[ -f "$env_file" ]] && env_old="$(cat "$env_file")"
  local env_new
  env_new="$(cat <<EOF
VLLM_IMAGE=$VLLM_IMAGE
VLLM_LLM_IMAGE=$VLLM_LLM_IMAGE
LLM_PROFILE=$LLM_PROFILE
PROXY_IMAGE=$PROXY_IMAGE
HF_TOKEN=${HF_TOKEN:-}
VLLM_API_KEY=$VLLM_API_KEY
MODELS_DIR=$MODELS_DIR
CACHE_DIR=$CACHE_DIR
BIND_IP=$SUITE_IP
LLM_MODEL=$LLM_MODEL
EMBED_MODEL=$EMBED_MODEL
LLM_PORT=$LLM_PORT
EMBED_PORT=$EMBED_PORT
PROXY_PORT=$PROXY_PORT
LLM_GPU_MEM_UTIL=$LLM_GPU_MEM_UTIL
EMBED_GPU_MEM_UTIL=$EMBED_GPU_MEM_UTIL
LLM_MAX_NUM_SEQS=$LLM_MAX_NUM_SEQS
LLM_MAX_MODEL_LEN=$LLM_MAX_MODEL_LEN
LLM_MTP_TOKENS=${LLM_MTP_TOKENS:-}
EMBED_MAX_MODEL_LEN=$EMBED_MAX_MODEL_LEN
VLLM_STT_IMAGE=$VLLM_STT_IMAGE
STT_MODEL=$LLM_STT_MODEL
STT_PORT=$STT_PORT
STT_GPU_MEM_UTIL=$LLM_STT_GPU_MEM_UTIL
STT_KV_CACHE_BYTES=$LLM_STT_KV_CACHE_BYTES
STT_MAX_MODEL_LEN=$LLM_STT_MAX_MODEL_LEN
STT_MAX_NUM_SEQS=$LLM_STT_MAX_NUM_SEQS
COMPOSE_PROFILES=${LLM_STT_MODEL:+stt}
EOF
)"
  ( umask 077; printf '%s\n' "$env_new" > "$env_file" )

  # Arms the .path unit that lets an org admin switch model from the app, and
  # writes the first state.json the UI reads. Idempotent, re-run on every
  # install — the fleet converges here, `update.sh` never replays deploy_vllm.
  # AFTER .env: switch-model.sh refuses to start without VLLM_IMAGE in it. Run
  # before, it failed on every FRESH install ("VLLM_IMAGE missing from …/.env")
  # — only a warning, so the box shipped with no llm-state bridge and the app's
  # model page stuck on "the appliance has not published its models yet".
  "$DATA_DIR/switch-model.sh" install-units \
    || warn "could not arm the model-switch trigger (the CLI still works)."

  # The unit template lives in switch-model.sh (install-vllm-unit): update.sh
  # rewrites it on a running box through the same path, so a box installed
  # before the CDI refresh gets it without a reinstall.
  CDI_SPEC="$CDI_SPEC" "$DATA_DIR/switch-model.sh" install-vllm-unit \
    || die "could not write suite366-vllm.service."
  # The unit is oneshot + RemainAfterExit: once active, `start` is a no-op, so a
  # re-run that changed .env (e.g. a new VLLM_API_KEY) would leave the running
  # containers on the stale config. Recreate them only when the config actually
  # changed; otherwise leave the stack up (avoids a needless multi-minute model
  # reload on an unchanged re-run).
  if ! systemctl is-active --quiet suite366-vllm.service; then
    systemctl start suite366-vllm.service
  elif [[ "$env_new" != "$env_old" ]]; then
    info "vLLM config changed — restarting the stack to apply it (models reload)."
    systemctl restart suite366-vllm.service
  else
    info "vLLM config unchanged — leaving the running stack in place."
  fi
  info "Downloading + loading models ($LLM_PROFILE; first boot for Flash-Next is ~133 GB, 25 min, then ~10 min to load)…"
  # Health-check on the stable internal IP: local, always reachable, offline-safe.
  if wait_http "http://$SUITE_IP:$LLM_PORT/health" "vLLM generative"; then
    warmup_chat "http://$SUITE_IP:$LLM_PORT" "$LLM_MODEL"
  else
    warn "vLLM generative not ready yet (see: docker logs suite366-vllm-llm)."
  fi
  if wait_http "http://$SUITE_IP:$EMBED_PORT/health" "vLLM embeddings"; then
    warmup_embed "http://$SUITE_IP:$EMBED_PORT" "$EMBED_MODEL"
  else
    warn "vLLM embeddings not ready yet (see: docker logs suite366-vllm-embed)."
  fi
  if [[ -n "$LLM_STT_MODEL" ]]; then
    if wait_http "http://$SUITE_IP:$STT_PORT/health" "vLLM transcription"; then
      warmup_stt "http://$SUITE_IP:$STT_PORT" "$LLM_STT_MODEL"
    else
      warn "vLLM transcription not ready yet (see: docker logs suite366-vllm-stt)."
    fi
  fi
  # The nginx proxy only becomes healthy once both vLLM backends are healthy
  # (depends_on: service_healthy). nginx itself starts in ~1s.
  if wait_http "http://$SUITE_IP:$PROXY_PORT/health" "vLLM unified proxy"; then
    info "  unified proxy ready at http://$SUITE_IP:$PROXY_PORT/v1"
  else
    warn "vLLM proxy not ready yet (see: docker logs suite366-vllm-proxy)."
  fi
}

# JIT warmup (Inductor/FlashInfer): without this, the first real request can
# take ~25s (cold codegen, cf. vLLM DGX Spark blog). We exercise the real path
# once so the first user doesn't pay this latency. Best-effort.
warmup_chat() { # warmup_chat BASE_URL MODEL
  local base="$1" model="$2"
  info "Warming up generative JIT (max_tokens=3)…"
  curl -fsS -m 120 "$base/v1/chat/completions" \
    -H "Authorization: Bearer $VLLM_API_KEY" -H "Content-Type: application/json" \
    -d "{\"model\":\"$model\",\"messages\":[{\"role\":\"user\",\"content\":\"ping\"}],\"max_tokens\":3}" \
    >/dev/null 2>&1 && info "  generative warm." || warn "  generative warmup skipped (curl failed, non-blocking)."
}
# Two seconds of a 440 Hz tone: enough to run the encoder and the decoder once.
# The transcript is noise; the point is the compiled kernels the first real
# dictation would otherwise wait for.
write_warmup_wav() { # write_warmup_wav PATH
  python3 - "$1" <<'PYW'
import math, struct, sys
sr = 16000; n = sr * 2
pcm = b''.join(struct.pack('<h', int(3000 * math.sin(2 * math.pi * 440 * i / sr))) for i in range(n))
hdr = (b'RIFF' + struct.pack('<I', 36 + len(pcm)) + b'WAVEfmt '
       + struct.pack('<IHHIIHH', 16, 1, 1, sr, sr * 2, 2, 16) + b'data' + struct.pack('<I', len(pcm)))
open(sys.argv[1], 'wb').write(hdr + pcm)
PYW
}
warmup_stt() { # warmup_stt BASE_URL MODEL
  local base="$1" model="$2" wav
  info "Warming up transcription JIT…"
  wav="$(mktemp --suffix=.wav)"
  if write_warmup_wav "$wav" && curl -fsS -m 300 "$base/v1/audio/transcriptions" \
       -H "Authorization: Bearer $VLLM_API_KEY" \
       -F "model=$model" -F "file=@$wav;type=audio/wav" >/dev/null 2>&1; then
    info "  transcription warm."
  else
    warn "  transcription warmup skipped (curl failed, non-blocking)."
  fi
  rm -f "$wav"
}
warmup_embed() { # warmup_embed BASE_URL MODEL
  local base="$1" model="$2"
  info "Warming up embeddings JIT…"
  curl -fsS -m 120 "$base/v1/embeddings" \
    -H "Authorization: Bearer $VLLM_API_KEY" -H "Content-Type: application/json" \
    -d "{\"model\":\"$model\",\"input\":\"ping\"}" \
    >/dev/null 2>&1 && info "  embeddings warm." || warn "  embeddings warmup skipped (curl failed, non-blocking)."
}
