# shellcheck shell=bash
# =============================================================================
# lib/vllm.sh — vLLM ×2 (generative + embeddings), ×3 with transcription, +
# nginx unifying proxy on the Docker host, wired to the Blackwell GPU and
# managed by a systemd unit.
# =============================================================================

# --- The host layer: one artefact, laid down whole -----------------------------
# Everything the vLLM stack needs on the host — switch-model.sh, the profile
# table, the compose, the nginx config, the container entrypoint, the Flash-Next
# patch set and the transcription image context — travels as ONE file,
# host-layer.sh (generated by tools/bundle-host-layer.sh, pinned in channel.json
# as host_layer_sha256). update.sh lays the same file down on a running box, so
# a fleet installed at different dates converges on the same host side without
# anyone re-running install.sh. The stamp records which bundle a box carries;
# update.sh compares it with the channel to know when to act.
#
# Laid down whatever the active profile: switching to Flash-Next later must not
# require reaching the deploy repo again, on a box that may have no route to it.
HOST_LAYER_STAMP="$DATA_DIR/llm/.host-layer.sha256"
fetch_host_layer() {
  local tmp; tmp="$(mktemp)"
  fetch "host-layer.sh" > "$tmp"
  bash -n "$tmp" || die "host-layer.sh does not parse — refusing to lay it down."
  bash "$tmp" extract "$DATA_DIR" || die "host-layer.sh could not unpack into $DATA_DIR."
  sha256sum "$tmp" | awk '{print $1}' > "$HOST_LAYER_STAMP"
  chmod 0644 "$HOST_LAYER_STAMP"
  rm -f "$tmp"
  info "host layer laid down (switch-model.sh + llm/, stamp $(cut -c1-12 "$HOST_LAYER_STAMP"))."
}

# --- Flash-Next: the patched vLLM image, built on the box ---------------------
# Qwen3.8-Flash-Next only fits on one Spark with its 47.7 GiB n-gram table served
# from the NVMe by mmap — a vLLM patch set (llm/flash-next/, vendored from
# blazux/qwen3.8-Flash-DGX) laid over the official v0.29.0 image. No registry
# holds that image: it is built here, once per (base image, patch commit) tag.
build_flash_next_image() { # build_flash_next_image TAG
  local tag="$1" ctx="$DATA_DIR/llm/flash-next"
  if docker image inspect "$tag" >/dev/null 2>&1; then
    info "vLLM image $tag already built."
    return 0
  fi
  log "Building $tag ($VLLM_IMAGE + the Flash-Next patch set, ~3 min)"
  docker pull -q "$VLLM_IMAGE" >/dev/null
  # stdout (the image id) is noise; stderr is where a failing step explains itself.
  docker build -q -t "$tag" "$ctx" >/dev/null \
    || die "docker build of $tag failed — see llm/flash-next/README.md"
}

# --- Transcription: the audio extras, built over the base image ---------------
# vllm/vllm-openai (arm64) decodes no audio at all without soundfile and PyAV
# (llm/stt/Dockerfile has the evidence). One thin layer, built here at install
# for the profiles that serve a transcription model, and by switch-model.sh
# when a later switch turns it on.
build_stt_image() { # build_stt_image TAG
  local tag="$1" ctx="$DATA_DIR/llm/stt"
  if docker image inspect "$tag" >/dev/null 2>&1; then
    info "vLLM transcription image $tag already built."
    return 0
  fi
  log "Building $tag ($VLLM_IMAGE + the audio extras, ~1 min)"
  docker pull -q "$VLLM_IMAGE" >/dev/null
  docker build -q --build-arg "BASE_IMAGE=$VLLM_IMAGE" -t "$tag" "$ctx" >/dev/null \
    || die "docker build of $tag failed — see llm/stt/Dockerfile"
}

# Only Flash-Next asks for this: with it up the box has no memory headroom
# (117/121 GiB used) and 7-10 GiB of swap in use, and at the default swappiness
# of 60 pages were read back from swap during every generation. The other two
# profiles leave the host default alone — and REMOVE the drop-in, so a box that
# switched away does not keep a tuning meant for a model it no longer runs.
VLLM_SYSCTL_FILE="${VLLM_SYSCTL_FILE:-/etc/sysctl.d/90-suite366-vllm.conf}"
apply_vllm_sysctl() { # apply_vllm_sysctl [SWAPPINESS]  (empty = restore default)
  local want="${1:-}"
  if [[ -z "$want" ]]; then
    [[ -f "$VLLM_SYSCTL_FILE" ]] || return 0
    rm -f "$VLLM_SYSCTL_FILE"
    info "vm.swappiness drop-in removed (this profile does not need it)."
    return 0
  fi
  printf 'vm.swappiness = %s\n' "$want" > "$VLLM_SYSCTL_FILE"
  sysctl -q -w "vm.swappiness=$want" >/dev/null 2>&1 || true
}

# --- 2. vLLM stack (Docker host) --------------------------------------------
deploy_vllm() {
  log "vLLM ×2 + nginx proxy (Docker host, Blackwell GPU)"
  # $CACHE_DIR holds the JIT state the compose mounts into both vLLM containers
  # (torch.compile artifacts, FlashInfer autotune + JIT cubins, Triton
  # kernels). It is what turns a 257 s restart into a 96 s one; safe to wipe.
  mkdir -p "$MODELS_DIR" "$DATA_DIR/llm" "$CACHE_DIR/vllm" "$CACHE_DIR/flashinfer" "$CACHE_DIR/triton"
  # The compose, the nginx config, switch-model.sh (an OPERATOR script, at
  # $DATA_DIR next to update.sh and backup.sh: `sudo /opt/suite366/switch-model.sh`),
  # the profile table, the entrypoint, Gemma's chat template and the two image
  # build contexts — one bundle, the same one update.sh lays down later.
  fetch_host_layer
  # `if`, not `[[ ]] &&`: as the last command of a function the && form
  # returns 1 when the test is false and `set -e` kills the install.
  if [[ "$LLM_P_NEEDS_BUILD" == "1" ]]; then build_flash_next_image "$VLLM_LLM_IMAGE"; fi
  if [[ -n "$LLM_STT_MODEL" ]]; then build_stt_image "$VLLM_STT_IMAGE"; fi
  apply_vllm_sysctl "$LLM_P_SWAPPINESS"
  # Arms the .path unit that lets an org admin switch model from the app, and
  # writes the first state.json the UI reads. Idempotent, re-run on every
  # install — the fleet converges here, `update.sh` never replays deploy_vllm.
  "$DATA_DIR/switch-model.sh" install-units \
    || warn "could not arm the model-switch trigger (the CLI still works)."
  local env_file="$DATA_DIR/llm/.env" env_old=""
  [[ -f "$env_file" ]] && env_old="$(cat "$env_file")"
  local env_new
  env_new="$(cat <<EOF
VLLM_IMAGE=$VLLM_IMAGE
VLLM_LLM_IMAGE=$VLLM_LLM_IMAGE
LLM_PROFILE=$LLM_PROFILE
PROXY_IMAGE=$PROXY_IMAGE
HF_TOKEN=${HF_TOKEN:-}
VLLM_API_KEY=$VLLM_API_KEY
MODELS_DIR=$MODELS_DIR
CACHE_DIR=$CACHE_DIR
BIND_IP=$SUITE_IP
LLM_MODEL=$LLM_MODEL
EMBED_MODEL=$EMBED_MODEL
LLM_PORT=$LLM_PORT
EMBED_PORT=$EMBED_PORT
PROXY_PORT=$PROXY_PORT
LLM_GPU_MEM_UTIL=$LLM_GPU_MEM_UTIL
EMBED_GPU_MEM_UTIL=$EMBED_GPU_MEM_UTIL
LLM_MAX_NUM_SEQS=$LLM_MAX_NUM_SEQS
LLM_MAX_MODEL_LEN=$LLM_MAX_MODEL_LEN
LLM_MTP_TOKENS=${LLM_MTP_TOKENS:-}
EMBED_MAX_MODEL_LEN=$EMBED_MAX_MODEL_LEN
VLLM_STT_IMAGE=$VLLM_STT_IMAGE
STT_MODEL=$LLM_STT_MODEL
STT_PORT=$STT_PORT
STT_GPU_MEM_UTIL=$LLM_STT_GPU_MEM_UTIL
STT_KV_CACHE_BYTES=$LLM_STT_KV_CACHE_BYTES
STT_MAX_MODEL_LEN=$LLM_STT_MAX_MODEL_LEN
STT_MAX_NUM_SEQS=$LLM_STT_MAX_NUM_SEQS
COMPOSE_PROFILES=${LLM_STT_MODEL:+stt}
EOF
)"
  ( umask 077; printf '%s\n' "$env_new" > "$env_file" )

  # The unit template lives in switch-model.sh (install-vllm-unit): update.sh
  # rewrites it on a running box through the same path, so a box installed
  # before the CDI refresh gets it without a reinstall.
  CDI_SPEC="$CDI_SPEC" "$DATA_DIR/switch-model.sh" install-vllm-unit \
    || die "could not write suite366-vllm.service."
  # The unit is oneshot + RemainAfterExit: once active, `start` is a no-op, so a
  # re-run that changed .env (e.g. a new VLLM_API_KEY) would leave the running
  # containers on the stale config. Recreate them only when the config actually
  # changed; otherwise leave the stack up (avoids a needless multi-minute model
  # reload on an unchanged re-run).
  if ! systemctl is-active --quiet suite366-vllm.service; then
    systemctl start suite366-vllm.service
  elif [[ "$env_new" != "$env_old" ]]; then
    info "vLLM config changed — restarting the stack to apply it (models reload)."
    systemctl restart suite366-vllm.service
  else
    info "vLLM config unchanged — leaving the running stack in place."
  fi
  info "Downloading + loading models ($LLM_PROFILE; first boot for Flash-Next is ~133 GB, 25 min, then ~10 min to load)…"
  # Health-check on the stable internal IP: local, always reachable, offline-safe.
  if wait_http "http://$SUITE_IP:$LLM_PORT/health" "vLLM generative"; then
    warmup_chat "http://$SUITE_IP:$LLM_PORT" "$LLM_MODEL"
  else
    warn "vLLM generative not ready yet (see: docker logs suite366-vllm-llm)."
  fi
  if wait_http "http://$SUITE_IP:$EMBED_PORT/health" "vLLM embeddings"; then
    warmup_embed "http://$SUITE_IP:$EMBED_PORT" "$EMBED_MODEL"
  else
    warn "vLLM embeddings not ready yet (see: docker logs suite366-vllm-embed)."
  fi
  if [[ -n "$LLM_STT_MODEL" ]]; then
    if wait_http "http://$SUITE_IP:$STT_PORT/health" "vLLM transcription"; then
      warmup_stt "http://$SUITE_IP:$STT_PORT" "$LLM_STT_MODEL"
    else
      warn "vLLM transcription not ready yet (see: docker logs suite366-vllm-stt)."
    fi
  fi
  # The nginx proxy only becomes healthy once both vLLM backends are healthy
  # (depends_on: service_healthy). nginx itself starts in ~1s.
  if wait_http "http://$SUITE_IP:$PROXY_PORT/health" "vLLM unified proxy"; then
    info "  unified proxy ready at http://$SUITE_IP:$PROXY_PORT/v1"
  else
    warn "vLLM proxy not ready yet (see: docker logs suite366-vllm-proxy)."
  fi
}

# JIT warmup (Inductor/FlashInfer): without this, the first real request can
# take ~25s (cold codegen, cf. vLLM DGX Spark blog). We exercise the real path
# once so the first user doesn't pay this latency. Best-effort.
warmup_chat() { # warmup_chat BASE_URL MODEL
  local base="$1" model="$2"
  info "Warming up generative JIT (max_tokens=3)…"
  curl -fsS -m 120 "$base/v1/chat/completions" \
    -H "Authorization: Bearer $VLLM_API_KEY" -H "Content-Type: application/json" \
    -d "{\"model\":\"$model\",\"messages\":[{\"role\":\"user\",\"content\":\"ping\"}],\"max_tokens\":3}" \
    >/dev/null 2>&1 && info "  generative warm." || warn "  generative warmup skipped (curl failed, non-blocking)."
}
# Two seconds of a 440 Hz tone: enough to run the encoder and the decoder once.
# The transcript is noise; the point is the compiled kernels the first real
# dictation would otherwise wait for.
write_warmup_wav() { # write_warmup_wav PATH
  python3 - "$1" <<'PYW'
import math, struct, sys
sr = 16000; n = sr * 2
pcm = b''.join(struct.pack('<h', int(3000 * math.sin(2 * math.pi * 440 * i / sr))) for i in range(n))
hdr = (b'RIFF' + struct.pack('<I', 36 + len(pcm)) + b'WAVEfmt '
       + struct.pack('<IHHIIHH', 16, 1, 1, sr, sr * 2, 2, 16) + b'data' + struct.pack('<I', len(pcm)))
open(sys.argv[1], 'wb').write(hdr + pcm)
PYW
}
warmup_stt() { # warmup_stt BASE_URL MODEL
  local base="$1" model="$2" wav
  info "Warming up transcription JIT…"
  wav="$(mktemp --suffix=.wav)"
  if write_warmup_wav "$wav" && curl -fsS -m 300 "$base/v1/audio/transcriptions" \
       -H "Authorization: Bearer $VLLM_API_KEY" \
       -F "model=$model" -F "file=@$wav;type=audio/wav" >/dev/null 2>&1; then
    info "  transcription warm."
  else
    warn "  transcription warmup skipped (curl failed, non-blocking)."
  fi
  rm -f "$wav"
}
warmup_embed() { # warmup_embed BASE_URL MODEL
  local base="$1" model="$2"
  info "Warming up embeddings JIT…"
  curl -fsS -m 120 "$base/v1/embeddings" \
    -H "Authorization: Bearer $VLLM_API_KEY" -H "Content-Type: application/json" \
    -d "{\"model\":\"$model\",\"input\":\"ping\"}" \
    >/dev/null 2>&1 && info "  embeddings warm." || warn "  embeddings warmup skipped (curl failed, non-blocking)."
}
