#!/usr/bin/env bash
# =============================================================================
# tools/bundle-host-layer.sh — build host-layer.sh, the one file an appliance
# fetches to receive everything the vLLM stack needs on the HOST.
#
# install.sh used to lay these files down one by one, and update.sh laid down
# none of them: a box updated through the channel got the app and the chart
# and kept the host it was installed with — no switch-model.sh, no profiles,
# no transcription, no CDI refresh in its vLLM unit. Seen on a client Spark at
# app 1.11.7 with the model page hidden, because the page needs a hostPath
# bridge only install.sh knew how to write.
#
# So the host layer is now ONE artefact, pinned in channel.json by
# `host_layer_sha256` exactly like update.sh and backup.sh, fetched and
# verified by update.sh and unpacked by `host-layer.sh extract DIR`. The
# payload is a deterministic gzip'd tar (sorted names, zero mtimes, numeric
# owner 0:0, `gzip -n`) so the same tree always yields the same bytes: CI
# regenerates it and fails when the committed copy is stale
# (tools/test-host-layer.sh).
#
# Usage:  tools/bundle-host-layer.sh            writes ./host-layer.sh
#         tools/bundle-host-layer.sh --stdout   prints it instead
#         tools/bundle-host-layer.sh --list     prints the files it would bundle
# =============================================================================
set -euo pipefail
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$REPO_ROOT/host-layer.sh"
MODE="${1:-write}"

# What the host layer IS: the operator script and everything under llm/ that
# the compose, the profiles or a build need on the box. Documentation stays
# in the repo: it is not read by anything on the appliance.
host_layer_files() {
  ( cd "$REPO_ROOT" && {
      printf '%s\n' switch-model.sh
      find llm -type f ! -name 'README.md' ! -name 'LICENSE.upstream'
    } | LC_ALL=C sort )
}

if [[ "$MODE" == "--list" ]]; then host_layer_files; exit 0; fi

mapfile -t FILES < <(host_layer_files)
[[ ${#FILES[@]} -gt 0 ]] || { echo "no files to bundle" >&2; exit 1; }
for f in "${FILES[@]}"; do [[ -f "$REPO_ROOT/$f" ]] || { echo "missing: $f" >&2; exit 1; }; done

payload="$(cd "$REPO_ROOT" && tar --sort=name --mtime='@0' --owner=0 --group=0 --numeric-owner \
             --format=gnu -cf - "${FILES[@]}" | gzip -n -9 | base64 -w 76)"

render() {
  cat <<'HDR'
#!/usr/bin/env bash
# =============================================================================
# host-layer.sh — GENERATED by tools/bundle-host-layer.sh. Do not edit by hand:
# edit the files under llm/ or switch-model.sh, then run the tool (CI fails on a
# stale copy). Everything the Suite 366 appliance needs on the HOST for its
# vLLM stack, in one file an updater can pin: switch-model.sh, the model
# profiles, the compose, the nginx proxy config, the container entrypoints and
# the image build contexts. Pinned in channel.json as `host_layer_sha256`
# (tools/sign-channel.sh), fetched and verified by update.sh, laid down by
# install.sh (lib/vllm.sh) and by update.sh (converge_host_layer).
#
#   host-layer.sh list            the files inside
#   host-layer.sh extract DIR     unpack them under DIR (DIR/switch-model.sh,
#                                 DIR/llm/...). Never touches DIR/llm/.env.
#
# The payload is a deterministic gzip'd tar, base64-encoded, carried in a
# quoted heredoc after the final `exit 0`: never executed, inert for shellcheck
# and `bash -n`, and read back by `extract` between its two marker lines.
# =============================================================================
set -euo pipefail
HDR
  printf 'HOST_LAYER_FILES="%s"\n' "${FILES[*]}"
  cat <<'BODY'
usage() { sed -n '/^#   host-layer.sh list/,/^#                                 DIR\/llm/p' "$0" | sed 's/^# \{0,1\}//'; }
case "${1:-}" in
  list) printf '%s\n' $HOST_LAYER_FILES ;;
  extract)
    dest="${2:-}"; [[ -n "$dest" ]] || { usage >&2; exit 2; }
    mkdir -p "$dest"
    sed -n "/^: <<'__PAYLOAD__'\$/,/^__PAYLOAD__\$/p" "$0" | sed '1d;$d' | base64 -d | tar -xzf - -C "$dest"
    # Modes the installer has always set: the operator script is root-only,
    # the entrypoints run inside the containers, everything else is data.
    find "$dest/llm" -type f -exec chmod 0644 {} +
    chmod 0755 "$dest/llm/serve-llm.sh"
    chmod 0750 "$dest/switch-model.sh"
    ;;
  *) usage >&2; exit 2 ;;
esac
exit 0
: <<'__PAYLOAD__'
BODY
  printf '%s\n' "$payload"
  printf '__PAYLOAD__\n'
}

if [[ "$MODE" == "--stdout" ]]; then render; exit 0; fi
tmp="$(mktemp)"; render > "$tmp"; bash -n "$tmp"
if [[ -f "$OUT" ]] && cmp -s "$tmp" "$OUT"; then
  echo "host-layer.sh unchanged (${#FILES[@]} files)"; rm -f "$tmp"
else
  install -m 0755 "$tmp" "$OUT"; rm -f "$tmp"
  echo "host-layer.sh written (${#FILES[@]} files, $(du -h "$OUT" | cut -f1))"
fi
